// Translations. en + hi poore hain. Baaki 15 bhashaon me core (customer + partner ke bade buttons) hain;
// jo key nahi milti wo English me dikhti hai. Native speaker se ek baar check zaroor karao.
type Dict = Record<string, string>;

const en: Dict = {
  lang_title: 'Choose your language', lang_sub: 'You can change it later', continue: 'Continue', login: 'Login', logout: 'Logout',
  phone: 'Mobile number', email: 'Email', otp: 'OTP', send_otp: 'Send OTP', verify: 'Verify', demo_otp: 'Demo mode: OTP is 123456',
  name: 'Your name', back: 'Back', save: 'Save', submit: 'Submit', cancel: 'Cancel', home: 'Home', loading: 'Loading...',
  empty: 'Nothing here yet', total: 'Total', subtotal: 'Subtotal', delivery_fee: 'Delivery fee', price: 'Price', stock: 'Stock',
  close: 'Close', yes: 'Yes', no: 'No', error: 'Something went wrong', invalid_phone: 'Enter a valid 10-digit mobile number',
  cat_all: 'All', cat_indoor: 'Indoor', cat_outdoor: 'Outdoor', cat_flowering: 'Flowering', cat_succulent: 'Succulent',
  cat_medicinal: 'Medicinal', cat_seeds: 'Seeds', cat_pots: 'Pots', cat_tools: 'Tools', cat_soil_manure: 'Soil & Manure',
  search_placeholder: 'Search plants, seeds, fertilizer', voice_search: 'Voice search', listening: 'Listening...',
  add_to_cart: 'Add to cart', added: 'Added to cart', cart: 'Cart', cart_empty: 'Your cart is empty', checkout: 'Checkout',
  address: 'Delivery address', pincode: 'Pincode', use_my_location: 'Use my location', delivery_partner: 'Delivery partner',
  cheapest: 'Cheapest', payment: 'Payment', cod: 'Cash on delivery', upi: 'UPI', place_order: 'Place order',
  order_placed: 'Order placed!', my_orders: 'My orders', track_order: 'Track order', cancel_order: 'Cancel order',
  cancel_window: 'You can cancel for {s}s', cancel_over: 'Cancel window is over', out_of_stock: 'Out of stock',
  nearby: 'Nearby nurseries', sold_by: 'Sold by {name}', verified: 'Verified', wishlist: 'Wishlist', identify_plant: 'Identify a plant',
  identify_hint: 'Take or upload a photo of any plant', become_partner: 'Become a Nursery Channel Partner',
  rate_order: 'Rate this order', claim_replacement: 'Plant died? Claim free replacement', festival_banner: 'Festival special',
  sort_nearest: 'Nearest', sort_cheapest: 'Cheapest', km_away: '{km} km away', qty: 'Qty', remove: 'Remove', account: 'Account',
  placed_on: 'Placed', no_nursery: 'No nursery can supply this right now', care: 'Care tips', ai_demo: 'AI suggestion (demo), may be wrong',
  pick_photo: 'Choose photo', share_whatsapp: 'Share on WhatsApp', support: 'Support on WhatsApp', login_to_order: 'Login to continue',
  order_for: 'Order from {name}', your_name_optional: 'Your name', claim_sent: 'Request sent. Our team will contact you.', review_sent: 'Thanks for your rating!',
  status_new: 'New', status_accepted: 'Accepted', status_packed: 'Packed', status_out_for_delivery: 'Out for delivery',
  status_delivered: 'Delivered', status_cancelled: 'Cancelled', status_rejected: 'Rejected', status_expired: 'Expired',
  // partner (Godown)
  partner_login: 'Partner login', pin: 'PIN (4-6 digits)', new_partner: 'NEW PARTNER? JOIN HERE', open_shop: 'OPEN SHOP',
  close_shop: 'CLOSE SHOP', shop_open: 'Shop is OPEN', shop_closed: 'Shop is CLOSED', yes_available: 'YES, AVAILABLE',
  not_available: 'NOT AVAILABLE', new_order: 'NEW ORDER', accept_within: 'Answer within', pack_now: 'PACK NOW', pack_done: 'PACKED',
  pack_hint: 'Pack the order. The delivery partner is coming.', earnings_today: 'Today', earnings_month: 'This month',
  earnings_pending: 'Pending', my_listings: 'My products', add_product: 'Add product', pending: 'Pending approval', live: 'Live',
  rejected: 'Rejected', product_name: 'Product name', upload_photo: 'Add photo', orders_today: 'Orders', no_orders: 'No orders yet',
  stock_on: 'In stock', stock_off: 'Out of stock', tier: 'Level', probation: 'New partner period until {date}', settings: 'Settings',
  language: 'Language', add_product_note: 'Your product goes live only after admin approval.', hello: 'Hello', orders: 'Orders',
  earnings: 'Earnings', listings: 'Products', category: 'Category', customer: 'Customer', items: 'Items', not_partner_yet: 'Your application is not approved yet.',
  // join wizard
  join_title: 'Become a Nursery Channel Partner', join_sub: 'Free to join. We verify you before you can sell.', step_type: 'Type', step_details: 'Details',
  step_docs: 'Documents', step_review: 'Review', choose_type: 'What do you want to sell from?',
  type_at_home: 'At Home', type_nursery: 'Nursery', type_fertilizer_shop: 'Fertilizer Shop', type_seed_shop: 'Seed Shop',
  type_at_home_docs: '1 ID + selfie + garden photo', type_nursery_docs: '1 ID + 2 nursery photos',
  type_fertilizer_shop_docs: '1 ID + shop photos + fertilizer licence + GST', type_seed_shop_docs: '1 ID + shop photos + GST/licence where required',
  shop_name: 'Shop / nursery name', owner_name: 'Owner name', whatsapp: 'WhatsApp number', city: 'City', upi_id: 'UPI ID (for payouts)',
  brand_suggestion: 'Brand name you want customers to see', choose_id: 'Choose ONE ID document',
  id_aadhaar_masked: 'Aadhaar (masked)', id_pan: 'PAN', id_residence_certificate: 'Residence certificate', id_driving_licence: 'Driving licence',
  id_passport: 'Passport', id_voter_id: 'Voter ID', doc_shop_photo_front: 'Shop front photo', doc_shop_photo_inside: 'Shop inside photo',
  doc_shop_front: 'Shop front photo', doc_shop_inside: 'Shop inside photo', doc_home_garden_photo: 'Home garden photo', doc_selfie: 'Selfie',
  doc_fertilizer_licence: 'Fertilizer licence photo', doc_seed_licence: 'Seed licence photo', doc_gst_certificate: 'GST certificate',
  licence_no: 'Licence number', licence_expiry: 'Licence expiry date', gst_no: 'GST number', aadhaar_hint: 'Aadhaar: hide the first 8 digits before taking the photo (masked Aadhaar).',
  take_photo: 'Take photo', photo_added: 'Photo added', consent_text: 'I allow NurseryFlower to use these documents only to verify me. They stay private, and rejected documents are deleted after 30 days.',
  consent_check: 'I agree', app_status_title: 'Application status', app_draft: 'Draft', app_submitted: 'Submitted', app_under_review: 'Under review',
  app_need_more_info: 'More information needed', app_approved: 'Approved', app_rejected: 'Rejected', sla_note: 'We reply within 48 hours.',
  resubmit: 'Fix and resubmit', go_dashboard: 'Go to my shop', next: 'Next', missing_fields: 'Please fill the required fields', register_account: 'Create partner account',
  have_account: 'Already have an account? Login', create_pin: 'Create a PIN', reason: 'Reason', admin_note: 'Note from admin',
};

const hi: Dict = {
  lang_title: 'अपनी भाषा चुनें', lang_sub: 'आप बाद में बदल सकते हैं', continue: 'आगे बढ़ें', login: 'लॉगिन', logout: 'लॉगआउट',
  phone: 'मोबाइल नंबर', email: 'ईमेल', otp: 'ओटीपी', send_otp: 'ओटीपी भेजें', verify: 'जाँचें', demo_otp: 'डेमो मोड: ओटीपी 123456 है',
  name: 'आपका नाम', back: 'पीछे', save: 'सेव करें', submit: 'जमा करें', cancel: 'रद्द करें', home: 'होम', loading: 'लोड हो रहा है...',
  empty: 'अभी कुछ नहीं है', total: 'कुल', subtotal: 'उप-कुल', delivery_fee: 'डिलीवरी शुल्क', price: 'कीमत', stock: 'स्टॉक',
  close: 'बंद करें', yes: 'हाँ', no: 'नहीं', error: 'कुछ गड़बड़ हो गई', invalid_phone: '10 अंकों का सही मोबाइल नंबर डालें',
  cat_all: 'सभी', cat_indoor: 'इनडोर', cat_outdoor: 'आउटडोर', cat_flowering: 'फूल वाले', cat_succulent: 'सक्यूलेंट',
  cat_medicinal: 'औषधीय', cat_seeds: 'बीज', cat_pots: 'गमले', cat_tools: 'औज़ार', cat_soil_manure: 'मिट्टी और खाद',
  search_placeholder: 'पौधे, बीज, खाद खोजें', voice_search: 'बोलकर खोजें', listening: 'सुन रहे हैं...',
  add_to_cart: 'कार्ट में डालें', added: 'कार्ट में डाल दिया', cart: 'कार्ट', cart_empty: 'आपका कार्ट खाली है', checkout: 'चेकआउट',
  address: 'डिलीवरी का पता', pincode: 'पिनकोड', use_my_location: 'मेरी लोकेशन लें', delivery_partner: 'डिलीवरी पार्टनर',
  cheapest: 'सबसे सस्ता', payment: 'भुगतान', cod: 'डिलीवरी पर नकद', upi: 'यूपीआई', place_order: 'ऑर्डर करें',
  order_placed: 'ऑर्डर हो गया!', my_orders: 'मेरे ऑर्डर', track_order: 'ऑर्डर ट्रैक करें', cancel_order: 'ऑर्डर रद्द करें',
  cancel_window: 'आप {s} सेकंड तक रद्द कर सकते हैं', cancel_over: 'रद्द करने का समय निकल गया', out_of_stock: 'स्टॉक खत्म',
  nearby: 'पास की नर्सरी', sold_by: 'विक्रेता: {name}', verified: 'वेरीफाइड', wishlist: 'पसंद की सूची', identify_plant: 'पौधा पहचानें',
  identify_hint: 'किसी भी पौधे की फोटो लें या डालें', become_partner: 'नर्सरी चैनल पार्टनर बनें',
  rate_order: 'इस ऑर्डर को रेटिंग दें', claim_replacement: 'पौधा मर गया? मुफ्त रिप्लेसमेंट लें', festival_banner: 'त्योहार विशेष',
  sort_nearest: 'सबसे पास', sort_cheapest: 'सबसे सस्ता', km_away: '{km} किमी दूर', qty: 'मात्रा', remove: 'हटाएँ', account: 'खाता',
  placed_on: 'ऑर्डर का समय', no_nursery: 'अभी कोई नर्सरी यह दे नहीं सकती', care: 'देखभाल के तरीके', ai_demo: 'एआई सुझाव (डेमो), गलत हो सकता है',
  pick_photo: 'फोटो चुनें', share_whatsapp: 'व्हाट्सऐप पर शेयर करें', support: 'व्हाट्सऐप सहायता', login_to_order: 'आगे बढ़ने के लिए लॉगिन करें',
  order_for: '{name} से ऑर्डर', your_name_optional: 'आपका नाम', claim_sent: 'अनुरोध भेज दिया। हमारी टीम संपर्क करेगी।', review_sent: 'रेटिंग के लिए धन्यवाद!',
  status_new: 'नया', status_accepted: 'स्वीकार', status_packed: 'पैक हो गया', status_out_for_delivery: 'डिलीवरी के लिए निकला',
  status_delivered: 'पहुँच गया', status_cancelled: 'रद्द', status_rejected: 'अस्वीकार', status_expired: 'समय समाप्त',
  partner_login: 'पार्टनर लॉगिन', pin: 'पिन (4-6 अंक)', new_partner: 'नए पार्टनर? यहाँ जुड़ें', open_shop: 'दुकान खोलें',
  close_shop: 'दुकान बंद करें', shop_open: 'दुकान खुली है', shop_closed: 'दुकान बंद है', yes_available: 'हाँ, है',
  not_available: 'नहीं है', new_order: 'नया ऑर्डर', accept_within: 'जवाब दें', pack_now: 'अभी पैक करें', pack_done: 'पैक हो गया',
  pack_hint: 'ऑर्डर पैक करें। डिलीवरी वाला आ रहा है।', earnings_today: 'आज', earnings_month: 'इस महीने',
  earnings_pending: 'बाकी', my_listings: 'मेरे प्रोडक्ट', add_product: 'प्रोडक्ट जोड़ें', pending: 'अप्रूवल बाकी', live: 'लाइव',
  rejected: 'अस्वीकार', product_name: 'प्रोडक्ट का नाम', upload_photo: 'फोटो जोड़ें', orders_today: 'ऑर्डर', no_orders: 'अभी कोई ऑर्डर नहीं',
  stock_on: 'स्टॉक में', stock_off: 'स्टॉक खत्म', tier: 'स्तर', probation: 'नया पार्टनर अवधि {date} तक', settings: 'सेटिंग्स',
  language: 'भाषा', add_product_note: 'आपका प्रोडक्ट एडमिन के अप्रूवल के बाद ही लाइव होगा।', hello: 'नमस्ते', orders: 'ऑर्डर',
  earnings: 'कमाई', listings: 'प्रोडक्ट', category: 'श्रेणी', customer: 'ग्राहक', items: 'सामान', not_partner_yet: 'आपका आवेदन अभी अप्रूव नहीं हुआ है।',
  join_title: 'नर्सरी चैनल पार्टनर बनें', join_sub: 'जुड़ना मुफ्त है। बेचने से पहले हम आपको वेरीफाई करते हैं।', step_type: 'प्रकार', step_details: 'जानकारी',
  step_docs: 'दस्तावेज़', step_review: 'जाँच', choose_type: 'आप कहाँ से बेचना चाहते हैं?',
  type_at_home: 'घर से', type_nursery: 'नर्सरी', type_fertilizer_shop: 'खाद की दुकान', type_seed_shop: 'बीज की दुकान',
  type_at_home_docs: '1 आईडी + सेल्फी + बगीचे की फोटो', type_nursery_docs: '1 आईडी + नर्सरी की 2 फोटो',
  type_fertilizer_shop_docs: '1 आईडी + दुकान की फोटो + खाद लाइसेंस + जीएसटी', type_seed_shop_docs: '1 आईडी + दुकान की फोटो + जहाँ ज़रूरी हो जीएसटी/लाइसेंस',
  shop_name: 'दुकान / नर्सरी का नाम', owner_name: 'मालिक का नाम', whatsapp: 'व्हाट्सऐप नंबर', city: 'शहर', upi_id: 'यूपीआई आईडी (भुगतान के लिए)',
  brand_suggestion: 'ग्राहक को जो ब्रांड नाम दिखाना है', choose_id: 'कोई भी एक आईडी चुनें',
  id_aadhaar_masked: 'आधार (मास्क्ड)', id_pan: 'पैन', id_residence_certificate: 'निवास प्रमाण पत्र', id_driving_licence: 'ड्राइविंग लाइसेंस',
  id_passport: 'पासपोर्ट', id_voter_id: 'वोटर आईडी', doc_shop_photo_front: 'दुकान के सामने की फोटो', doc_shop_photo_inside: 'दुकान के अंदर की फोटो',
  doc_shop_front: 'दुकान के सामने की फोटो', doc_shop_inside: 'दुकान के अंदर की फोटो', doc_home_garden_photo: 'घर के बगीचे की फोटो', doc_selfie: 'सेल्फी',
  doc_fertilizer_licence: 'खाद लाइसेंस की फोटो', doc_seed_licence: 'बीज लाइसेंस की फोटो', doc_gst_certificate: 'जीएसटी प्रमाण पत्र',
  licence_no: 'लाइसेंस नंबर', licence_expiry: 'लाइसेंस की समाप्ति तारीख', gst_no: 'जीएसटी नंबर', aadhaar_hint: 'आधार: फोटो खींचने से पहले शुरू के 8 अंक ढक दें (मास्क्ड आधार)।',
  take_photo: 'फोटो लें', photo_added: 'फोटो जुड़ गई', consent_text: 'मैं नर्सरीफ्लावर को ये दस्तावेज़ सिर्फ मेरी जाँच के लिए इस्तेमाल करने की अनुमति देता/देती हूँ। ये निजी रहेंगे और रद्द हुए आवेदन के दस्तावेज़ 30 दिन बाद मिटा दिए जाएँगे।',
  consent_check: 'मैं सहमत हूँ', app_status_title: 'आवेदन की स्थिति', app_draft: 'ड्राफ्ट', app_submitted: 'जमा हो गया', app_under_review: 'जाँच चल रही है',
  app_need_more_info: 'और जानकारी चाहिए', app_approved: 'अप्रूव हो गया', app_rejected: 'अस्वीकार', sla_note: 'हम 48 घंटे में जवाब देते हैं।',
  resubmit: 'सुधारकर दोबारा जमा करें', go_dashboard: 'मेरी दुकान पर जाएँ', next: 'आगे', missing_fields: 'ज़रूरी जानकारी भरें', register_account: 'पार्टनर खाता बनाएँ',
  have_account: 'पहले से खाता है? लॉगिन करें', create_pin: 'पिन बनाएँ', reason: 'कारण', admin_note: 'एडमिन का संदेश',
};

const bn: Dict = { lang_title: 'আপনার ভাষা বেছে নিন', continue: 'চালিয়ে যান', login: 'লগইন', logout: 'লগআউট', phone: 'মোবাইল নম্বর', otp: 'ওটিপি', send_otp: 'ওটিপি পাঠান', verify: 'যাচাই করুন', name: 'আপনার নাম', back: 'পিছনে', home: 'হোম', cart: 'কার্ট', checkout: 'চেকআউট', total: 'মোট', search_placeholder: 'গাছ, বীজ, সার খুঁজুন', add_to_cart: 'কার্টে যোগ করুন', cart_empty: 'আপনার কার্ট খালি', place_order: 'অর্ডার করুন', my_orders: 'আমার অর্ডার', address: 'ঠিকানা', cod: 'ক্যাশ অন ডেলিভারি', delivery_fee: 'ডেলিভারি চার্জ', out_of_stock: 'স্টক নেই', become_partner: 'নার্সারি চ্যানেল পার্টনার হোন', cancel_order: 'অর্ডার বাতিল', cat_all: 'সব', cat_indoor: 'ঘরের ভেতরের', cat_outdoor: 'বাইরের', cat_flowering: 'ফুলের গাছ', cat_succulent: 'সাকুলেন্ট', cat_medicinal: 'ঔষধি', cat_seeds: 'বীজ', cat_pots: 'টব', cat_tools: 'সরঞ্জাম', cat_soil_manure: 'মাটি ও সার', status_new: 'নতুন', status_accepted: 'গৃহীত', status_packed: 'প্যাক হয়েছে', status_out_for_delivery: 'ডেলিভারির পথে', status_delivered: 'পৌঁছে গেছে', status_cancelled: 'বাতিল', open_shop: 'দোকান খুলুন', close_shop: 'দোকান বন্ধ করুন', yes_available: 'হ্যাঁ, আছে', not_available: 'নেই', new_order: 'নতুন অর্ডার', pack_now: 'এখন প্যাক করুন', earnings_today: 'আজকের আয়' };
const ta: Dict = { lang_title: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்', continue: 'தொடரவும்', login: 'உள்நுழை', logout: 'வெளியேறு', phone: 'மொபைல் எண்', otp: 'ஓடிபி', send_otp: 'ஓடிபி அனுப்பு', verify: 'சரிபார்', name: 'உங்கள் பெயர்', back: 'பின்', home: 'முகப்பு', cart: 'கூடை', checkout: 'பணம் செலுத்து', total: 'மொத்தம்', search_placeholder: 'செடிகள், விதைகள், உரம் தேடுங்கள்', add_to_cart: 'கூடையில் சேர்', cart_empty: 'கூடை காலியாக உள்ளது', place_order: 'ஆர்டர் செய்', my_orders: 'என் ஆர்டர்கள்', address: 'முகவரி', cod: 'டெலிவரியில் பணம்', delivery_fee: 'டெலிவரி கட்டணம்', out_of_stock: 'இருப்பு இல்லை', become_partner: 'நர்சரி சேனல் பார்ட்னர் ஆகுங்கள்', cancel_order: 'ஆர்டரை ரத்து செய்', cat_all: 'அனைத்தும்', cat_indoor: 'உள்அலங்காரச் செடிகள்', cat_outdoor: 'வெளிப்புறச் செடிகள்', cat_flowering: 'பூச்செடிகள்', cat_succulent: 'கற்றாழை வகைகள்', cat_medicinal: 'மூலிகைச் செடிகள்', cat_seeds: 'விதைகள்', cat_pots: 'தொட்டிகள்', cat_tools: 'கருவிகள்', cat_soil_manure: 'மண் & உரம்', status_new: 'புதியது', status_accepted: 'ஏற்கப்பட்டது', status_packed: 'பேக் செய்யப்பட்டது', status_out_for_delivery: 'டெலிவரிக்கு புறப்பட்டது', status_delivered: 'வழங்கப்பட்டது', status_cancelled: 'ரத்து', open_shop: 'கடையைத் திற', close_shop: 'கடையை மூடு', yes_available: 'ஆம், உள்ளது', not_available: 'இல்லை', new_order: 'புதிய ஆர்டர்', pack_now: 'இப்போது பேக் செய்', earnings_today: 'இன்றைய வருமானம்' };
const te: Dict = { lang_title: 'మీ భాషను ఎంచుకోండి', continue: 'కొనసాగించు', login: 'లాగిన్', logout: 'లాగౌట్', phone: 'మొబైల్ నంబర్', otp: 'ఓటీపీ', send_otp: 'ఓటీపీ పంపండి', verify: 'ధృవీకరించు', name: 'మీ పేరు', back: 'వెనుకకు', home: 'హోమ్', cart: 'కార్ట్', checkout: 'చెక్అవుట్', total: 'మొత్తం', search_placeholder: 'మొక్కలు, విత్తనాలు, ఎరువు వెతకండి', add_to_cart: 'కార్ట్‌లో చేర్చు', cart_empty: 'మీ కార్ట్ ఖాళీగా ఉంది', place_order: 'ఆర్డర్ చేయండి', my_orders: 'నా ఆర్డర్లు', address: 'చిరునామా', cod: 'డెలివరీ సమయంలో నగదు', delivery_fee: 'డెలివరీ ఛార్జీ', out_of_stock: 'స్టాక్ లేదు', become_partner: 'నర్సరీ ఛానల్ పార్టనర్ అవ్వండి', cancel_order: 'ఆర్డర్ రద్దు', cat_all: 'అన్నీ', cat_indoor: 'ఇండోర్', cat_outdoor: 'అవుట్‌డోర్', cat_flowering: 'పూల మొక్కలు', cat_succulent: 'సక్యులెంట్లు', cat_medicinal: 'ఔషధ మొక్కలు', cat_seeds: 'విత్తనాలు', cat_pots: 'కుండీలు', cat_tools: 'పనిముట్లు', cat_soil_manure: 'మట్టి & ఎరువు', status_new: 'కొత్తది', status_accepted: 'అంగీకరించబడింది', status_packed: 'ప్యాక్ అయింది', status_out_for_delivery: 'డెలివరీకి బయలుదేరింది', status_delivered: 'అందింది', status_cancelled: 'రద్దయింది', open_shop: 'షాప్ తెరవండి', close_shop: 'షాప్ మూసివేయండి', yes_available: 'అవును, ఉంది', not_available: 'లేదు', new_order: 'కొత్త ఆర్డర్', pack_now: 'ఇప్పుడు ప్యాక్ చేయండి', earnings_today: 'ఈ రోజు ఆదాయం' };
const mr: Dict = { lang_title: 'तुमची भाषा निवडा', continue: 'पुढे जा', login: 'लॉगिन', logout: 'लॉगआउट', phone: 'मोबाइल नंबर', otp: 'ओटीपी', send_otp: 'ओटीपी पाठवा', verify: 'तपासा', name: 'तुमचे नाव', back: 'मागे', home: 'मुख्यपृष्ठ', cart: 'कार्ट', checkout: 'चेकआउट', total: 'एकूण', search_placeholder: 'रोपे, बिया, खत शोधा', add_to_cart: 'कार्टमध्ये टाका', cart_empty: 'तुमचे कार्ट रिकामे आहे', place_order: 'ऑर्डर द्या', my_orders: 'माझे ऑर्डर', address: 'पत्ता', cod: 'डिलिव्हरीवर रोख', delivery_fee: 'डिलिव्हरी शुल्क', out_of_stock: 'स्टॉक नाही', become_partner: 'नर्सरी चॅनल पार्टनर व्हा', cancel_order: 'ऑर्डर रद्द करा', cat_all: 'सर्व', cat_indoor: 'घरातील', cat_outdoor: 'बाहेरील', cat_flowering: 'फुलझाडे', cat_succulent: 'रसाळ वनस्पती', cat_medicinal: 'औषधी', cat_seeds: 'बिया', cat_pots: 'कुंड्या', cat_tools: 'अवजारे', cat_soil_manure: 'माती व खत', status_new: 'नवीन', status_accepted: 'स्वीकारले', status_packed: 'पॅक झाले', status_out_for_delivery: 'डिलिव्हरीसाठी निघाले', status_delivered: 'पोहोचले', status_cancelled: 'रद्द', open_shop: 'दुकान उघडा', close_shop: 'दुकान बंद करा', yes_available: 'होय, आहे', not_available: 'नाही', new_order: 'नवीन ऑर्डर', pack_now: 'आता पॅक करा', earnings_today: 'आजची कमाई' };
const gu: Dict = { lang_title: 'તમારી ભાષા પસંદ કરો', continue: 'આગળ વધો', login: 'લૉગિન', logout: 'લૉગઆઉટ', phone: 'મોબાઇલ નંબર', otp: 'ઓટીપી', send_otp: 'ઓટીપી મોકલો', verify: 'ચકાસો', name: 'તમારું નામ', back: 'પાછા', home: 'હોમ', cart: 'કાર્ટ', checkout: 'ચેકઆઉટ', total: 'કુલ', search_placeholder: 'છોડ, બીજ, ખાતર શોધો', add_to_cart: 'કાર્ટમાં ઉમેરો', cart_empty: 'તમારું કાર્ટ ખાલી છે', place_order: 'ઓર્ડર આપો', my_orders: 'મારા ઓર્ડર', address: 'સરનામું', cod: 'ડિલિવરી પર રોકડ', delivery_fee: 'ડિલિવરી ચાર્જ', out_of_stock: 'સ્ટોક નથી', become_partner: 'નર્સરી ચેનલ પાર્ટનર બનો', cancel_order: 'ઓર્ડર રદ કરો', cat_all: 'બધું', cat_indoor: 'ઘરની અંદરના', cat_outdoor: 'બહારના', cat_flowering: 'ફૂલછોડ', cat_succulent: 'સક્યુલન્ટ', cat_medicinal: 'ઔષધીય', cat_seeds: 'બીજ', cat_pots: 'કુંડા', cat_tools: 'સાધનો', cat_soil_manure: 'માટી અને ખાતર', status_new: 'નવો', status_accepted: 'સ્વીકાર્યો', status_packed: 'પેક થયો', status_out_for_delivery: 'ડિલિવરી માટે નીકળ્યો', status_delivered: 'પહોંચ્યો', status_cancelled: 'રદ', open_shop: 'દુકાન ખોલો', close_shop: 'દુકાન બંધ કરો', yes_available: 'હા, છે', not_available: 'નથી', new_order: 'નવો ઓર્ડર', pack_now: 'હવે પેક કરો', earnings_today: 'આજની કમાણી' };
const kn: Dict = { lang_title: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ', continue: 'ಮುಂದುವರಿಸಿ', login: 'ಲಾಗಿನ್', logout: 'ಲಾಗೌಟ್', phone: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ', otp: 'ಒಟಿಪಿ', send_otp: 'ಒಟಿಪಿ ಕಳುಹಿಸಿ', verify: 'ಪರಿಶೀಲಿಸಿ', name: 'ನಿಮ್ಮ ಹೆಸರು', back: 'ಹಿಂದೆ', home: 'ಮುಖಪುಟ', cart: 'ಕಾರ್ಟ್', checkout: 'ಚೆಕ್‌ಔಟ್', total: 'ಒಟ್ಟು', search_placeholder: 'ಗಿಡ, ಬೀಜ, ಗೊಬ್ಬರ ಹುಡುಕಿ', add_to_cart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ', cart_empty: 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ', place_order: 'ಆರ್ಡರ್ ಮಾಡಿ', my_orders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು', address: 'ವಿಳಾಸ', cod: 'ಡೆಲಿವರಿ ವೇಳೆ ನಗದು', delivery_fee: 'ಡೆಲಿವರಿ ಶುಲ್ಕ', out_of_stock: 'ಸ್ಟಾಕ್ ಇಲ್ಲ', become_partner: 'ನರ್ಸರಿ ಚಾನೆಲ್ ಪಾರ್ಟ್ನರ್ ಆಗಿ', cancel_order: 'ಆರ್ಡರ್ ರದ್ದುಮಾಡಿ', cat_all: 'ಎಲ್ಲಾ', cat_indoor: 'ಒಳಾಂಗಣ', cat_outdoor: 'ಹೊರಾಂಗಣ', cat_flowering: 'ಹೂವಿನ ಗಿಡಗಳು', cat_succulent: 'ಸಕ್ಯುಲೆಂಟ್', cat_medicinal: 'ಔಷಧೀಯ', cat_seeds: 'ಬೀಜಗಳು', cat_pots: 'ಕುಂಡಗಳು', cat_tools: 'ಉಪಕರಣಗಳು', cat_soil_manure: 'ಮಣ್ಣು ಮತ್ತು ಗೊಬ್ಬರ', status_new: 'ಹೊಸದು', status_accepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ', status_packed: 'ಪ್ಯಾಕ್ ಆಗಿದೆ', status_out_for_delivery: 'ಡೆಲಿವರಿಗೆ ಹೊರಟಿದೆ', status_delivered: 'ತಲುಪಿದೆ', status_cancelled: 'ರದ್ದು', open_shop: 'ಅಂಗಡಿ ತೆರೆಯಿರಿ', close_shop: 'ಅಂಗಡಿ ಮುಚ್ಚಿ', yes_available: 'ಹೌದು, ಇದೆ', not_available: 'ಇಲ್ಲ', new_order: 'ಹೊಸ ಆರ್ಡರ್', pack_now: 'ಈಗ ಪ್ಯಾಕ್ ಮಾಡಿ', earnings_today: 'ಇಂದಿನ ಗಳಿಕೆ' };
const ml: Dict = { lang_title: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക', continue: 'തുടരുക', login: 'ലോഗിൻ', logout: 'ലോഗൗട്ട്', phone: 'മൊബൈൽ നമ്പർ', otp: 'ഒടിപി', send_otp: 'ഒടിപി അയയ്ക്കുക', verify: 'സ്ഥിരീകരിക്കുക', name: 'നിങ്ങളുടെ പേര്', back: 'തിരികെ', home: 'ഹോം', cart: 'കാർട്ട്', checkout: 'ചെക്ക്ഔട്ട്', total: 'ആകെ', search_placeholder: 'ചെടികൾ, വിത്തുകൾ, വളം തിരയുക', add_to_cart: 'കാർട്ടിൽ ചേർക്കുക', cart_empty: 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്', place_order: 'ഓർഡർ ചെയ്യുക', my_orders: 'എന്റെ ഓർഡറുകൾ', address: 'വിലാസം', cod: 'ഡെലിവറിയിൽ പണം', delivery_fee: 'ഡെലിവറി ചാർജ്', out_of_stock: 'സ്റ്റോക്ക് ഇല്ല', become_partner: 'നഴ്സറി ചാനൽ പാർട്ണർ ആകുക', cancel_order: 'ഓർഡർ റദ്ദാക്കുക', cat_all: 'എല്ലാം', cat_indoor: 'ഇൻഡോർ', cat_outdoor: 'ഔട്ട്ഡോർ', cat_flowering: 'പൂച്ചെടികൾ', cat_succulent: 'സക്കുലന്റ്', cat_medicinal: 'ഔഷധസസ്യങ്ങൾ', cat_seeds: 'വിത്തുകൾ', cat_pots: 'ചട്ടികൾ', cat_tools: 'ഉപകരണങ്ങൾ', cat_soil_manure: 'മണ്ണും വളവും', status_new: 'പുതിയത്', status_accepted: 'സ്വീകരിച്ചു', status_packed: 'പായ്ക്ക് ചെയ്തു', status_out_for_delivery: 'ഡെലിവറിക്കായി പുറപ്പെട്ടു', status_delivered: 'എത്തിച്ചു', status_cancelled: 'റദ്ദാക്കി', open_shop: 'കട തുറക്കുക', close_shop: 'കട അടയ്ക്കുക', yes_available: 'ഉണ്ട്', not_available: 'ഇല്ല', new_order: 'പുതിയ ഓർഡർ', pack_now: 'ഇപ്പോൾ പായ്ക്ക് ചെയ്യുക', earnings_today: 'ഇന്നത്തെ വരുമാനം' };
const pa: Dict = { lang_title: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ', continue: 'ਅੱਗੇ ਵਧੋ', login: 'ਲੌਗਇਨ', logout: 'ਲੌਗਆਊਟ', phone: 'ਮੋਬਾਈਲ ਨੰਬਰ', otp: 'ਓਟੀਪੀ', send_otp: 'ਓਟੀਪੀ ਭੇਜੋ', verify: 'ਤਸਦੀਕ ਕਰੋ', name: 'ਤੁਹਾਡਾ ਨਾਮ', back: 'ਪਿੱਛੇ', home: 'ਹੋਮ', cart: 'ਕਾਰਟ', checkout: 'ਚੈੱਕਆਉਟ', total: 'ਕੁੱਲ', search_placeholder: 'ਬੂਟੇ, ਬੀਜ, ਖਾਦ ਲੱਭੋ', add_to_cart: 'ਕਾਰਟ ਵਿੱਚ ਪਾਓ', cart_empty: 'ਤੁਹਾਡਾ ਕਾਰਟ ਖਾਲੀ ਹੈ', place_order: 'ਆਰਡਰ ਕਰੋ', my_orders: 'ਮੇਰੇ ਆਰਡਰ', address: 'ਪਤਾ', cod: 'ਡਿਲੀਵਰੀ ਤੇ ਨਕਦ', delivery_fee: 'ਡਿਲੀਵਰੀ ਚਾਰਜ', out_of_stock: 'ਸਟਾਕ ਨਹੀਂ', become_partner: 'ਨਰਸਰੀ ਚੈਨਲ ਪਾਰਟਨਰ ਬਣੋ', cancel_order: 'ਆਰਡਰ ਰੱਦ ਕਰੋ', cat_all: 'ਸਭ', cat_indoor: 'ਘਰ ਅੰਦਰ ਦੇ', cat_outdoor: 'ਬਾਹਰ ਦੇ', cat_flowering: 'ਫੁੱਲਾਂ ਵਾਲੇ', cat_succulent: 'ਸੁਕੂਲੈਂਟ', cat_medicinal: 'ਦਵਾਈ ਵਾਲੇ', cat_seeds: 'ਬੀਜ', cat_pots: 'ਗਮਲੇ', cat_tools: 'ਸੰਦ', cat_soil_manure: 'ਮਿੱਟੀ ਤੇ ਖਾਦ', status_new: 'ਨਵਾਂ', status_accepted: 'ਮਨਜ਼ੂਰ', status_packed: 'ਪੈਕ ਹੋ ਗਿਆ', status_out_for_delivery: 'ਡਿਲੀਵਰੀ ਲਈ ਨਿਕਲਿਆ', status_delivered: 'ਪਹੁੰਚ ਗਿਆ', status_cancelled: 'ਰੱਦ', open_shop: 'ਦੁਕਾਨ ਖੋਲ੍ਹੋ', close_shop: 'ਦੁਕਾਨ ਬੰਦ ਕਰੋ', yes_available: 'ਹਾਂ, ਹੈ', not_available: 'ਨਹੀਂ ਹੈ', new_order: 'ਨਵਾਂ ਆਰਡਰ', pack_now: 'ਹੁਣ ਪੈਕ ਕਰੋ', earnings_today: 'ਅੱਜ ਦੀ ਕਮਾਈ' };
const ur: Dict = { lang_title: 'اپنی زبان منتخب کریں', continue: 'جاری رکھیں', login: 'لاگ اِن', logout: 'لاگ آؤٹ', phone: 'موبائل نمبر', otp: 'او ٹی پی', send_otp: 'او ٹی پی بھیجیں', verify: 'تصدیق کریں', name: 'آپ کا نام', back: 'واپس', home: 'ہوم', cart: 'کارٹ', checkout: 'چیک آؤٹ', total: 'کل', search_placeholder: 'پودے، بیج، کھاد تلاش کریں', add_to_cart: 'کارٹ میں ڈالیں', cart_empty: 'آپ کا کارٹ خالی ہے', place_order: 'آرڈر کریں', my_orders: 'میرے آرڈر', address: 'پتہ', cod: 'ڈیلیوری پر نقد', delivery_fee: 'ڈیلیوری چارج', out_of_stock: 'اسٹاک ختم', become_partner: 'نرسری چینل پارٹنر بنیں', cancel_order: 'آرڈر منسوخ کریں', cat_all: 'سب', cat_indoor: 'گھر کے اندر', cat_outdoor: 'باہر کے', cat_flowering: 'پھولدار', cat_succulent: 'سکیولنٹ', cat_medicinal: 'دواؤں والے', cat_seeds: 'بیج', cat_pots: 'گملے', cat_tools: 'اوزار', cat_soil_manure: 'مٹی اور کھاد', status_new: 'نیا', status_accepted: 'قبول', status_packed: 'پیک ہو گیا', status_out_for_delivery: 'ڈیلیوری کے لیے روانہ', status_delivered: 'پہنچ گیا', status_cancelled: 'منسوخ', open_shop: 'دکان کھولیں', close_shop: 'دکان بند کریں', yes_available: 'جی ہاں، موجود ہے', not_available: 'موجود نہیں', new_order: 'نیا آرڈر', pack_now: 'ابھی پیک کریں', earnings_today: 'آج کی کمائی' };
const es: Dict = { lang_title: 'Elige tu idioma', continue: 'Continuar', login: 'Iniciar sesión', logout: 'Cerrar sesión', phone: 'Número de móvil', otp: 'Código OTP', send_otp: 'Enviar OTP', verify: 'Verificar', name: 'Tu nombre', back: 'Atrás', home: 'Inicio', cart: 'Carrito', checkout: 'Pagar', total: 'Total', search_placeholder: 'Buscar plantas, semillas, abono', add_to_cart: 'Añadir al carrito', cart_empty: 'Tu carrito está vacío', place_order: 'Hacer pedido', my_orders: 'Mis pedidos', address: 'Dirección', cod: 'Pago contra entrega', delivery_fee: 'Gastos de envío', out_of_stock: 'Agotado', become_partner: 'Sé socio de vivero', cancel_order: 'Cancelar pedido', cat_all: 'Todo', cat_indoor: 'Interior', cat_outdoor: 'Exterior', cat_flowering: 'Con flores', cat_succulent: 'Suculentas', cat_medicinal: 'Medicinales', cat_seeds: 'Semillas', cat_pots: 'Macetas', cat_tools: 'Herramientas', cat_soil_manure: 'Tierra y abono', status_new: 'Nuevo', status_accepted: 'Aceptado', status_packed: 'Empaquetado', status_out_for_delivery: 'En camino', status_delivered: 'Entregado', status_cancelled: 'Cancelado', open_shop: 'ABRIR TIENDA', close_shop: 'CERRAR TIENDA', yes_available: 'SÍ, DISPONIBLE', not_available: 'NO DISPONIBLE', new_order: 'NUEVO PEDIDO', pack_now: 'EMPAQUETAR', earnings_today: 'Ganancias de hoy' };
const fr: Dict = { lang_title: 'Choisissez votre langue', continue: 'Continuer', login: 'Connexion', logout: 'Déconnexion', phone: 'Numéro de mobile', otp: 'Code OTP', send_otp: 'Envoyer l’OTP', verify: 'Vérifier', name: 'Votre nom', back: 'Retour', home: 'Accueil', cart: 'Panier', checkout: 'Paiement', total: 'Total', search_placeholder: 'Chercher plantes, graines, engrais', add_to_cart: 'Ajouter au panier', cart_empty: 'Votre panier est vide', place_order: 'Commander', my_orders: 'Mes commandes', address: 'Adresse', cod: 'Paiement à la livraison', delivery_fee: 'Frais de livraison', out_of_stock: 'Rupture de stock', become_partner: 'Devenir partenaire pépinière', cancel_order: 'Annuler la commande', cat_all: 'Tout', cat_indoor: 'Intérieur', cat_outdoor: 'Extérieur', cat_flowering: 'À fleurs', cat_succulent: 'Succulentes', cat_medicinal: 'Médicinales', cat_seeds: 'Graines', cat_pots: 'Pots', cat_tools: 'Outils', cat_soil_manure: 'Terre et engrais', status_new: 'Nouvelle', status_accepted: 'Acceptée', status_packed: 'Emballée', status_out_for_delivery: 'En livraison', status_delivered: 'Livrée', status_cancelled: 'Annulée', open_shop: 'OUVRIR LA BOUTIQUE', close_shop: 'FERMER LA BOUTIQUE', yes_available: 'OUI, DISPONIBLE', not_available: 'NON DISPONIBLE', new_order: 'NOUVELLE COMMANDE', pack_now: 'EMBALLER', earnings_today: 'Gains du jour' };
const de: Dict = { lang_title: 'Sprache wählen', continue: 'Weiter', login: 'Anmelden', logout: 'Abmelden', phone: 'Handynummer', otp: 'OTP-Code', send_otp: 'OTP senden', verify: 'Bestätigen', name: 'Ihr Name', back: 'Zurück', home: 'Start', cart: 'Warenkorb', checkout: 'Zur Kasse', total: 'Gesamt', search_placeholder: 'Pflanzen, Samen, Dünger suchen', add_to_cart: 'In den Warenkorb', cart_empty: 'Ihr Warenkorb ist leer', place_order: 'Bestellen', my_orders: 'Meine Bestellungen', address: 'Adresse', cod: 'Nachnahme', delivery_fee: 'Liefergebühr', out_of_stock: 'Nicht vorrätig', become_partner: 'Gärtnerei-Partner werden', cancel_order: 'Bestellung stornieren', cat_all: 'Alle', cat_indoor: 'Zimmerpflanzen', cat_outdoor: 'Gartenpflanzen', cat_flowering: 'Blühpflanzen', cat_succulent: 'Sukkulenten', cat_medicinal: 'Heilpflanzen', cat_seeds: 'Samen', cat_pots: 'Töpfe', cat_tools: 'Werkzeug', cat_soil_manure: 'Erde & Dünger', status_new: 'Neu', status_accepted: 'Angenommen', status_packed: 'Verpackt', status_out_for_delivery: 'Unterwegs', status_delivered: 'Geliefert', status_cancelled: 'Storniert', open_shop: 'SHOP ÖFFNEN', close_shop: 'SHOP SCHLIESSEN', yes_available: 'JA, VERFÜGBAR', not_available: 'NICHT VERFÜGBAR', new_order: 'NEUE BESTELLUNG', pack_now: 'JETZT PACKEN', earnings_today: 'Heutiger Verdienst' };
const ar: Dict = { lang_title: 'اختر لغتك', continue: 'متابعة', login: 'تسجيل الدخول', logout: 'تسجيل الخروج', phone: 'رقم الجوال', otp: 'رمز التحقق', send_otp: 'إرسال الرمز', verify: 'تحقق', name: 'اسمك', back: 'رجوع', home: 'الرئيسية', cart: 'السلة', checkout: 'الدفع', total: 'الإجمالي', search_placeholder: 'ابحث عن نباتات، بذور، سماد', add_to_cart: 'أضف إلى السلة', cart_empty: 'سلتك فارغة', place_order: 'اطلب الآن', my_orders: 'طلباتي', address: 'العنوان', cod: 'الدفع عند الاستلام', delivery_fee: 'رسوم التوصيل', out_of_stock: 'غير متوفر', become_partner: 'كن شريك مشتل', cancel_order: 'إلغاء الطلب', cat_all: 'الكل', cat_indoor: 'نباتات داخلية', cat_outdoor: 'نباتات خارجية', cat_flowering: 'نباتات مزهرة', cat_succulent: 'عصاريات', cat_medicinal: 'نباتات طبية', cat_seeds: 'بذور', cat_pots: 'أصص', cat_tools: 'أدوات', cat_soil_manure: 'تربة وسماد', status_new: 'جديد', status_accepted: 'مقبول', status_packed: 'تم التغليف', status_out_for_delivery: 'في الطريق', status_delivered: 'تم التسليم', status_cancelled: 'ملغى', open_shop: 'افتح المتجر', close_shop: 'أغلق المتجر', yes_available: 'نعم، متوفر', not_available: 'غير متوفر', new_order: 'طلب جديد', pack_now: 'جهّز الآن', earnings_today: 'أرباح اليوم' };
const pt: Dict = { lang_title: 'Escolha seu idioma', continue: 'Continuar', login: 'Entrar', logout: 'Sair', phone: 'Número de celular', otp: 'Código OTP', send_otp: 'Enviar OTP', verify: 'Verificar', name: 'Seu nome', back: 'Voltar', home: 'Início', cart: 'Carrinho', checkout: 'Finalizar', total: 'Total', search_placeholder: 'Buscar plantas, sementes, adubo', add_to_cart: 'Adicionar ao carrinho', cart_empty: 'Seu carrinho está vazio', place_order: 'Fazer pedido', my_orders: 'Meus pedidos', address: 'Endereço', cod: 'Pagamento na entrega', delivery_fee: 'Taxa de entrega', out_of_stock: 'Esgotado', become_partner: 'Seja parceiro de viveiro', cancel_order: 'Cancelar pedido', cat_all: 'Tudo', cat_indoor: 'Interior', cat_outdoor: 'Exterior', cat_flowering: 'Com flores', cat_succulent: 'Suculentas', cat_medicinal: 'Medicinais', cat_seeds: 'Sementes', cat_pots: 'Vasos', cat_tools: 'Ferramentas', cat_soil_manure: 'Terra e adubo', status_new: 'Novo', status_accepted: 'Aceito', status_packed: 'Embalado', status_out_for_delivery: 'Saiu para entrega', status_delivered: 'Entregue', status_cancelled: 'Cancelado', open_shop: 'ABRIR LOJA', close_shop: 'FECHAR LOJA', yes_available: 'SIM, DISPONÍVEL', not_available: 'INDISPONÍVEL', new_order: 'NOVO PEDIDO', pack_now: 'EMBALAR AGORA', earnings_today: 'Ganhos de hoje' };
const zh: Dict = { lang_title: '选择语言', continue: '继续', login: '登录', logout: '退出登录', phone: '手机号', otp: '验证码', send_otp: '发送验证码', verify: '验证', name: '您的姓名', back: '返回', home: '首页', cart: '购物车', checkout: '结算', total: '合计', search_placeholder: '搜索植物、种子、肥料', add_to_cart: '加入购物车', cart_empty: '购物车是空的', place_order: '下单', my_orders: '我的订单', address: '地址', cod: '货到付款', delivery_fee: '配送费', out_of_stock: '缺货', become_partner: '成为苗圃合作伙伴', cancel_order: '取消订单', cat_all: '全部', cat_indoor: '室内植物', cat_outdoor: '室外植物', cat_flowering: '开花植物', cat_succulent: '多肉植物', cat_medicinal: '药用植物', cat_seeds: '种子', cat_pots: '花盆', cat_tools: '工具', cat_soil_manure: '土壤与肥料', status_new: '新订单', status_accepted: '已接单', status_packed: '已打包', status_out_for_delivery: '配送中', status_delivered: '已送达', status_cancelled: '已取消', open_shop: '开店', close_shop: '关店', yes_available: '有货', not_available: '没货', new_order: '新订单', pack_now: '立即打包', earnings_today: '今日收入' };

export const DICT: Record<string, Dict> = { en, hi, bn, ta, te, mr, gu, kn, ml, pa, ur, es, fr, de, ar, pt, zh };
